using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stocker.Modules.Finance.Application.DTOs;
using Stocker.Modules.Finance.Application.Features.JournalEntries.Commands;
using Stocker.Modules.Finance.Application.Features.JournalEntries.Queries;
using Stocker.Modules.Finance.Domain.Entities;
using Stocker.SharedKernel.Authorization;
using Stocker.SharedKernel.Pagination;
using Stocker.SharedKernel.Results;

namespace Stocker.Modules.Finance.API.Controllers;

/// <summary>
/// Yevmiye Kaydı (Journal Entry) API Controller
/// </summary>
[ApiController]
[Authorize]
[Route("api/finance/journal-entries")]
[RequireModule("Finance")]
[ApiExplorerSettings(GroupName = "finance")]
public class JournalEntriesController : ControllerBase
{
    private readonly IMediator _mediator;

    public JournalEntriesController(IMediator mediator)
    {
        _mediator = mediator;
    }

    /// <summary>
    /// Get paginated journal entries
    /// </summary>
    [HttpGet]
    [ProducesResponseType(typeof(PagedResult<JournalEntrySummaryDto>), 200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<PagedResult<JournalEntrySummaryDto>>> GetJournalEntries(
        [FromQuery] int pageNumber = 1,
        [FromQuery] int pageSize = 20,
        [FromQuery] string? searchTerm = null,
        [FromQuery] int? entryType = null,
        [FromQuery] int? status = null,
        [FromQuery] DateTime? startDate = null,
        [FromQuery] DateTime? endDate = null,
        [FromQuery] int? accountingPeriodId = null,
        [FromQuery] int? accountId = null,
        [FromQuery] bool? isAutoGenerated = null,
        [FromQuery] bool? isReversal = null,
        [FromQuery] string? sortBy = null,
        [FromQuery] bool sortDescending = true)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var query = new GetJournalEntriesQuery
        {
            TenantId = tenantId.Value,
            Filter = new JournalEntryFilterDto
            {
                PageNumber = pageNumber,
                PageSize = pageSize,
                SearchTerm = searchTerm,
                EntryType = entryType.HasValue ? (JournalEntryType)entryType.Value : null,
                Status = status.HasValue ? (JournalEntryStatus)status.Value : null,
                StartDate = startDate,
                EndDate = endDate,
                AccountingPeriodId = accountingPeriodId,
                AccountId = accountId,
                IsAutoGenerated = isAutoGenerated,
                IsReversal = isReversal,
                SortBy = sortBy,
                SortDescending = sortDescending
            }
        };

        var result = await _mediator.Send(query);

        if (result.IsFailure)
            return BadRequest(result.Error);

        return Ok(result.Value);
    }

    /// <summary>
    /// Get journal entry by ID
    /// </summary>
    [HttpGet("{id}")]
    [ProducesResponseType(typeof(JournalEntryDto), 200)]
    [ProducesResponseType(404)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<JournalEntryDto>> GetJournalEntry(int id)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var query = new GetJournalEntryByIdQuery
        {
            TenantId = tenantId.Value,
            Id = id
        };

        var result = await _mediator.Send(query);

        if (result.IsFailure)
        {
            if (result.Error.Type == ErrorType.NotFound)
                return NotFound(result.Error);
            return BadRequest(result.Error);
        }

        return Ok(result.Value);
    }

    /// <summary>
    /// Get journal entries by type
    /// </summary>
    [HttpGet("by-type/{entryType}")]
    [ProducesResponseType(typeof(PagedResult<JournalEntrySummaryDto>), 200)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<PagedResult<JournalEntrySummaryDto>>> GetJournalEntriesByType(
        int entryType,
        [FromQuery] int pageNumber = 1,
        [FromQuery] int pageSize = 20)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var query = new GetJournalEntriesByTypeQuery
        {
            TenantId = tenantId.Value,
            EntryType = (JournalEntryType)entryType,
            PageNumber = pageNumber,
            PageSize = pageSize
        };

        var result = await _mediator.Send(query);

        if (result.IsFailure)
            return BadRequest(result.Error);

        return Ok(result.Value);
    }

    /// <summary>
    /// Get journal entries by status
    /// </summary>
    [HttpGet("by-status/{status}")]
    [ProducesResponseType(typeof(PagedResult<JournalEntrySummaryDto>), 200)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<PagedResult<JournalEntrySummaryDto>>> GetJournalEntriesByStatus(
        int status,
        [FromQuery] int pageNumber = 1,
        [FromQuery] int pageSize = 20)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var query = new GetJournalEntriesByStatusQuery
        {
            TenantId = tenantId.Value,
            Status = (JournalEntryStatus)status,
            PageNumber = pageNumber,
            PageSize = pageSize
        };

        var result = await _mediator.Send(query);

        if (result.IsFailure)
            return BadRequest(result.Error);

        return Ok(result.Value);
    }

    /// <summary>
    /// Get journal entries by accounting period
    /// </summary>
    [HttpGet("by-period/{periodId}")]
    [ProducesResponseType(typeof(PagedResult<JournalEntrySummaryDto>), 200)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<PagedResult<JournalEntrySummaryDto>>> GetJournalEntriesByPeriod(
        int periodId,
        [FromQuery] int pageNumber = 1,
        [FromQuery] int pageSize = 20)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var query = new GetJournalEntriesByPeriodQuery
        {
            TenantId = tenantId.Value,
            AccountingPeriodId = periodId,
            PageNumber = pageNumber,
            PageSize = pageSize
        };

        var result = await _mediator.Send(query);

        if (result.IsFailure)
            return BadRequest(result.Error);

        return Ok(result.Value);
    }

    /// <summary>
    /// Get journal entries by reference
    /// </summary>
    [HttpGet("by-reference")]
    [ProducesResponseType(typeof(List<JournalEntrySummaryDto>), 200)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<List<JournalEntrySummaryDto>>> GetJournalEntriesByReference(
        [FromQuery] string referenceType,
        [FromQuery] int referenceId)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var query = new GetJournalEntriesByReferenceQuery
        {
            TenantId = tenantId.Value,
            ReferenceType = referenceType,
            ReferenceId = referenceId
        };

        var result = await _mediator.Send(query);

        if (result.IsFailure)
            return BadRequest(result.Error);

        return Ok(result.Value);
    }

    /// <summary>
    /// Get journal entry statistics
    /// </summary>
    [HttpGet("statistics")]
    [ProducesResponseType(typeof(JournalEntryStatisticsDto), 200)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<JournalEntryStatisticsDto>> GetStatistics(
        [FromQuery] DateTime? startDate = null,
        [FromQuery] DateTime? endDate = null,
        [FromQuery] int? accountingPeriodId = null)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var query = new GetJournalEntryStatisticsQuery
        {
            TenantId = tenantId.Value,
            StartDate = startDate,
            EndDate = endDate,
            AccountingPeriodId = accountingPeriodId
        };

        var result = await _mediator.Send(query);

        if (result.IsFailure)
            return BadRequest(result.Error);

        return Ok(result.Value);
    }

    /// <summary>
    /// Create a new journal entry
    /// </summary>
    [HttpPost]
    [ProducesResponseType(typeof(JournalEntryDto), 201)]
    [ProducesResponseType(400)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<JournalEntryDto>> CreateJournalEntry([FromBody] CreateJournalEntryDto dto)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var command = new CreateJournalEntryCommand
        {
            TenantId = tenantId.Value,
            Data = dto
        };

        var result = await _mediator.Send(command);

        if (result.IsFailure)
            return BadRequest(result.Error);

        return CreatedAtAction(nameof(GetJournalEntry), new { id = result.Value.Id }, result.Value);
    }

    /// <summary>
    /// Update a journal entry
    /// </summary>
    [HttpPut("{id}")]
    [ProducesResponseType(typeof(JournalEntryDto), 200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<JournalEntryDto>> UpdateJournalEntry(int id, [FromBody] UpdateJournalEntryDto dto)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var command = new UpdateJournalEntryCommand
        {
            TenantId = tenantId.Value,
            Id = id,
            Data = dto
        };

        var result = await _mediator.Send(command);

        if (result.IsFailure)
        {
            if (result.Error.Type == ErrorType.NotFound)
                return NotFound(result.Error);
            return BadRequest(result.Error);
        }

        return Ok(result.Value);
    }

    /// <summary>
    /// Submit journal entry for approval
    /// </summary>
    [HttpPost("{id}/submit")]
    [ProducesResponseType(typeof(JournalEntryDto), 200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<JournalEntryDto>> SubmitJournalEntry(int id)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var command = new SubmitJournalEntryCommand
        {
            TenantId = tenantId.Value,
            Id = id
        };

        var result = await _mediator.Send(command);

        if (result.IsFailure)
        {
            if (result.Error.Type == ErrorType.NotFound)
                return NotFound(result.Error);
            return BadRequest(result.Error);
        }

        return Ok(result.Value);
    }

    /// <summary>
    /// Approve a journal entry
    /// </summary>
    [HttpPost("{id}/approve")]
    [ProducesResponseType(typeof(JournalEntryDto), 200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<JournalEntryDto>> ApproveJournalEntry(int id, [FromBody] ApproveJournalEntryDto dto)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var command = new ApproveJournalEntryCommand
        {
            TenantId = tenantId.Value,
            Id = id,
            ApprovedBy = dto.ApprovedBy
        };

        var result = await _mediator.Send(command);

        if (result.IsFailure)
        {
            if (result.Error.Type == ErrorType.NotFound)
                return NotFound(result.Error);
            return BadRequest(result.Error);
        }

        return Ok(result.Value);
    }

    /// <summary>
    /// Reject a journal entry
    /// </summary>
    [HttpPost("{id}/reject")]
    [ProducesResponseType(typeof(JournalEntryDto), 200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<JournalEntryDto>> RejectJournalEntry(int id, [FromBody] RejectJournalEntryDto dto)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var command = new RejectJournalEntryCommand
        {
            TenantId = tenantId.Value,
            Id = id,
            Reason = dto.Reason
        };

        var result = await _mediator.Send(command);

        if (result.IsFailure)
        {
            if (result.Error.Type == ErrorType.NotFound)
                return NotFound(result.Error);
            return BadRequest(result.Error);
        }

        return Ok(result.Value);
    }

    /// <summary>
    /// Post a journal entry to ledger
    /// </summary>
    [HttpPost("{id}/post")]
    [ProducesResponseType(typeof(JournalEntryDto), 200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<JournalEntryDto>> PostJournalEntry(int id)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var command = new PostJournalEntryCommand
        {
            TenantId = tenantId.Value,
            Id = id
        };

        var result = await _mediator.Send(command);

        if (result.IsFailure)
        {
            if (result.Error.Type == ErrorType.NotFound)
                return NotFound(result.Error);
            return BadRequest(result.Error);
        }

        return Ok(result.Value);
    }

    /// <summary>
    /// Void a journal entry
    /// </summary>
    [HttpPost("{id}/void")]
    [ProducesResponseType(typeof(JournalEntryDto), 200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<JournalEntryDto>> VoidJournalEntry(int id, [FromQuery] string? reason = null)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var command = new VoidJournalEntryCommand
        {
            TenantId = tenantId.Value,
            Id = id,
            Reason = reason
        };

        var result = await _mediator.Send(command);

        if (result.IsFailure)
        {
            if (result.Error.Type == ErrorType.NotFound)
                return NotFound(result.Error);
            return BadRequest(result.Error);
        }

        return Ok(result.Value);
    }

    /// <summary>
    /// Create a reversal entry
    /// </summary>
    [HttpPost("{id}/reverse")]
    [ProducesResponseType(typeof(JournalEntryDto), 201)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    [ProducesResponseType(401)]
    public async Task<ActionResult<JournalEntryDto>> CreateReversalEntry(int id, [FromBody] CreateReversalEntryDto dto)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var command = new CreateReversalEntryCommand
        {
            TenantId = tenantId.Value,
            OriginalEntryId = id,
            ReversalDate = dto.ReversalDate,
            Description = dto.Description
        };

        var result = await _mediator.Send(command);

        if (result.IsFailure)
        {
            if (result.Error.Type == ErrorType.NotFound)
                return NotFound(result.Error);
            return BadRequest(result.Error);
        }

        return CreatedAtAction(nameof(GetJournalEntry), new { id = result.Value.Id }, result.Value);
    }

    /// <summary>
    /// Delete a journal entry
    /// </summary>
    [HttpDelete("{id}")]
    [ProducesResponseType(204)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    [ProducesResponseType(401)]
    public async Task<IActionResult> DeleteJournalEntry(int id)
    {
        var tenantId = HttpContext.Items["TenantId"] as Guid?;
        if (!tenantId.HasValue)
            return BadRequest(new Error("Tenant.Required", "Tenant ID is required", ErrorType.Validation));

        var command = new DeleteJournalEntryCommand
        {
            TenantId = tenantId.Value,
            Id = id
        };

        var result = await _mediator.Send(command);

        if (result.IsFailure)
        {
            if (result.Error.Type == ErrorType.NotFound)
                return NotFound(result.Error);
            return BadRequest(result.Error);
        }

        return NoContent();
    }
}
