version: '3.8'

# MinIO Object Storage - Public Access Version
# This configuration exposes MinIO on minio.stoocker.app

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    # ports kısmını kaldırabilirsiniz, Traefik üzerinden erişim sağlanacak
    # ports:
    #   - "9000:9000"  # API port
    #   - "9001:9001"  # Console port
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER=on
      - MINIO_DOMAIN=minio.stoocker.app
      - MINIO_SERVER_URL=https://minio.stoocker.app
      - MINIO_BROWSER_REDIRECT_URL=https://console.minio.stoocker.app
    volumes:
      - minio_data:/data
    networks:
      - coolify
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      
      # MinIO API (S3 compatible) - HTTPS
      - "traefik.http.routers.minio-api-secure.rule=Host(`minio.stoocker.app`) || Host(`s3.stoocker.app`)"
      - "traefik.http.routers.minio-api-secure.entrypoints=https"
      - "traefik.http.routers.minio-api-secure.tls=true"
      - "traefik.http.routers.minio-api-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.minio-api-secure.tls.domains[0].main=stoocker.app"
      - "traefik.http.routers.minio-api-secure.tls.domains[0].sans=*.stoocker.app"
      - "traefik.http.routers.minio-api-secure.service=minio-api"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"
      
      # MinIO API - HTTP redirect
      - "traefik.http.routers.minio-api.rule=Host(`minio.stoocker.app`) || Host(`s3.stoocker.app`)"
      - "traefik.http.routers.minio-api.entrypoints=http"
      - "traefik.http.routers.minio-api.middlewares=redirect-to-https"
      
      # MinIO Console (Web UI) - HTTPS
      - "traefik.http.routers.minio-console-secure.rule=Host(`console.minio.stoocker.app`)"
      - "traefik.http.routers.minio-console-secure.entrypoints=https"
      - "traefik.http.routers.minio-console-secure.tls=true"
      - "traefik.http.routers.minio-console-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.minio-console-secure.tls.domains[0].main=stoocker.app"
      - "traefik.http.routers.minio-console-secure.tls.domains[0].sans=*.stoocker.app"
      - "traefik.http.routers.minio-console-secure.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      
      # MinIO Console - HTTP redirect  
      - "traefik.http.routers.minio-console.rule=Host(`console.minio.stoocker.app`)"
      - "traefik.http.routers.minio-console.entrypoints=http"
      - "traefik.http.routers.minio-console.middlewares=redirect-to-https"
      
      # Middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      
      # Coolify labels
      - "coolify.managed=true"
      - "coolify.type=service"
      - "coolify.name=minio"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  minio_data:
    driver: local

networks:
  coolify:
    external: true