version: '3.8'

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - CLOUDFLARE_EMAIL=anilberk199751@gmail.com
      - CLOUDFLARE_API_KEY=295600b8132d530e289d11cef34dd1d1ed8a7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./traefik/certs:/certs
      - ./traefik/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.stoocker.app`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  web:
    image: ghcr.io/abrkgrbz/stocker-web:latest
    container_name: stocker-web
    restart: unless-stopped
    networks:
      - web
    environment:
      - VITE_API_URL=https://api.stoocker.app
      - VITE_APP_URL=https://stoocker.app
      - VITE_MOCK_ENABLED=false
    labels:
      - "traefik.enable=true"
      # Ana domain
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.rule=Host(`stoocker.app`) || Host(`www.stoocker.app`)"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=cloudflare"
      - "traefik.http.routers.web.priority=10"
      # Wildcard routing
      - "traefik.http.routers.web-wildcard.entrypoints=websecure"
      - "traefik.http.routers.web-wildcard.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.stoocker.app`)"
      - "traefik.http.routers.web-wildcard.tls=true"
      - "traefik.http.routers.web-wildcard.tls.certresolver=cloudflare"
      - "traefik.http.routers.web-wildcard.tls.domains[0].main=stoocker.app"
      - "traefik.http.routers.web-wildcard.tls.domains[0].sans=*.stoocker.app"
      - "traefik.http.routers.web-wildcard.priority=5"
      # Service
      - "traefik.http.services.web.loadbalancer.server.port=80"