version: '3.8'

services:
  alertmanager:
    build:
      context: ./alertmanager
      dockerfile: Dockerfile.simple  # Use simple config first for testing
      # dockerfile: Dockerfile       # Switch to this for dynamic config
    container_name: stocker-alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    environment:
      # Environment variables for dynamic config (when using main Dockerfile)
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-}
      - FROM_EMAIL=${FROM_EMAIL:-alerts@stoocker.app}
      - SMTP_HOST=${SMTP_HOST:-smtp.sendgrid.net}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-apikey}
      - ALERT_EMAIL=${ALERT_EMAIL:-admin@stoocker.app}
      - EXTERNAL_URL=https://alerts.stoocker.app
    volumes:
      # Only data volume, config is in Docker image
      - alertmanager_data:/alertmanager
    networks:
      - stocker-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  alertmanager_data:
    driver: local

networks:
  stocker-network:
    external: true