version: '3.8'

# Optional services for development
services:
  # Database Admin UI
  adminer:
    image: adminer:latest
    container_name: stocker-adminer
    ports:
      - "8090:8080"
    networks:
      - stocker-network
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula