version: '3.8'

services:
  # MSSQL Database
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: stocker-mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID:-Developer}
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433" 
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${SA_PASSWORD}' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # CloudBeaver - Database Management UI
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: stocker-cloudbeaver
    environment:
      CB_ADMIN_NAME: ${CB_ADMIN_NAME:-admin}
      CB_ADMIN_PASSWORD: ${CB_ADMIN_PASSWORD:-admin123}
    ports:
      - "${CLOUDBEAVER_PORT:-8978}:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8978"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    links:
      - mssql:database

  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stocker-api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__MasterConnection: "Server=stocker-mssql,1433;Database=StockerMasterDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true;Encrypt=false"
      ConnectionStrings__TenantConnection: "Server=stocker-mssql,1433;Database=StockerTenantDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true;Encrypt=false"
      ConnectionStrings__DefaultConnection: "Server=stocker-mssql,1433;Database=StockerTenantDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true;Encrypt=false"
      JwtSettings__SecretKey: ${JWT_SECRET_KEY}
      EmailSettings__SmtpHost: ${SMTP_HOST:-smtp.gmail.com}
      EmailSettings__SmtpPort: ${SMTP_PORT:-587}
      EmailSettings__SmtpUser: ${SMTP_USER}
      EmailSettings__SmtpPassword: ${SMTP_PASSWORD}
      EmailSettings__FromEmail: ${FROM_EMAIL:-noreply@stocker.com}
      EmailSettings__FromName: ${FROM_NAME:-Stocker}
    depends_on:
      - mssql
    ports:
      - "${API_PORT:-5000}:5000" 
    volumes:
      - ./logs:/app/logs
      - ./emails:/app/emails
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    links:
      - mssql:database

volumes:
  mssql_data:
    driver: local
  cloudbeaver_data:
    driver: local