version: '3.8'

networks:
  stocker-network:
    driver: bridge

services:
  # MSSQL Database
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: stocker-database
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID:-Developer}
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433" 
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${SA_PASSWORD}' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - stocker-network

  # CloudBeaver - Database Management UI
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: stocker-cloudbeaver
    environment:
      CB_ADMIN_NAME: ${CB_ADMIN_NAME}
      CB_ADMIN_PASSWORD: ${CB_ADMIN_PASSWORD}
    ports:
      - "${CLOUDBEAVER_PORT:-8978}:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - stocker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8978"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Web Application
  web:
    build:
      context: ./stocker-web
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://95.217.219.4:5000
    container_name: stocker-web
    ports:
      - "${WEB_PORT:-80}:80"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - stocker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stocker-api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__MasterConnection: "${ConnectionStrings__MasterConnection}"
      ConnectionStrings__TenantConnection: "${ConnectionStrings__TenantConnection}"
      ConnectionStrings__DefaultConnection: "${ConnectionStrings__DefaultConnection}"
      JwtSettings__Secret: ${JWT_SECRET_KEY}
      EmailSettings__SmtpHost: ${SMTP_HOST:-smtp.gmail.com}
      EmailSettings__SmtpPort: ${SMTP_PORT:-587}
      EmailSettings__SmtpUser: ${SMTP_USER}
      EmailSettings__SmtpPassword: ${SMTP_PASSWORD}
      EmailSettings__FromEmail: ${FROM_EMAIL:-noreply@stocker.com}
      EmailSettings__FromName: ${FROM_NAME:-Stocker}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${API_PORT:-5000}:5000" 
    volumes:
      - ./logs:/app/logs
      - ./emails:/app/emails
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - stocker-network
volumes:
  mssql_data:
    driver: local
  cloudbeaver_data:
    driver: local