version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/API/Stocker.API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      # Database connections - Update these with your actual database host
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      - ConnectionStrings__MasterConnection=${MASTER_DB_CONNECTION}
      - ConnectionStrings__TenantConnection=${TENANT_DB_CONNECTION}
      # Database Settings for dynamic tenant database creation
      - DatabaseSettings__ServerName=${DB_SERVER}
      - DatabaseSettings__UserId=${DB_USER}
      - DatabaseSettings__Password=${DB_PASSWORD}
      # JWT Settings
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=https://api.stoocker.app
      - JwtSettings__Audience=https://stoocker.app
      - JwtSettings__AccessTokenExpirationMinutes=60
      - JwtSettings__RefreshTokenExpirationDays=7
      # Email Settings
      - EmailSettings__SmtpHost=mail.privateemail.com
      - EmailSettings__SmtpPort=465
      - EmailSettings__SmtpUsername=info@stoocker.app
      - EmailSettings__SmtpPassword=${EMAIL_PASSWORD}
      - EmailSettings__EnableSsl=true
      - EmailSettings__FromEmail=info@stoocker.app
      - EmailSettings__FromName=Stoocker
      - EmailSettings__UseStartTls=false
      - EmailSettings__EnableEmail=true
      - EmailSettings__BaseUrl=https://stoocker.app
      - EmailSettings__TemplatesPath=EmailTemplates
      - EmailSettings__Timeout=30000
      # Redis connection - Update with your actual Redis host
      - Redis__ConnectionString=${REDIS_CONNECTION}
      - ConnectionStrings__Redis=${REDIS_CONNECTION}
      # Hangfire Settings
      - Hangfire__DashboardPath=/hangfire
      - Hangfire__ServerName=Stocker-Production
      - Hangfire__WorkerCount=8
      - Hangfire__Queues__0=critical
      - Hangfire__Queues__1=default
      - Hangfire__Queues__2=low
      - Hangfire__RetryAttempts=3
      - Hangfire__JobExpirationCheckInterval=01:00:00
      - Hangfire__CountersAggregateInterval=00:05:00
      # Seq Logging Settings
      - Logging__Seq__ServerUrl=http://seq:5341
      - Logging__Seq__ApiKey=
      - Logging__Seq__MinimumLevel=Information
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - stocker-network

networks:
  stocker-network:
    driver: bridge
 