version: '3.8'

services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: stocker-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      # Only data volume, config is in Docker image
      - prometheus_data:/prometheus
    networks:
      - stocker-network
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  prometheus_data:
    driver: local

networks:
  stocker-network:
    external: true