version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrongPassw0rd2024"  # Özel karakter kullanmadan
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: |
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrongPassw0rd2024" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  api:
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__MasterConnection: "Server=mssql;Database=StockerMasterDb;User Id=sa;Password=YourStrongPassw0rd2024;TrustServerCertificate=True;"
      ConnectionStrings__TenantConnectionTemplate: "Server=mssql;Database={0};User Id=sa;Password=YourStrongPassw0rd2024;TrustServerCertificate=True;"
      Jwt__Key: "${JWT_SECRET_KEY:-your-very-secure-secret-key-min-256-bits}"
      Jwt__Issuer: "StockerAPI"
      Jwt__Audience: "StockerClient"
      EmailConfiguration__From: "${FROM_EMAIL:-noreply@yourdomain.com}"
      EmailConfiguration__SmtpServer: "${SMTP_HOST:-smtp.gmail.com}"
      EmailConfiguration__Port: "${SMTP_PORT:-587}"
      EmailConfiguration__Username: "${SMTP_USER}"
      EmailConfiguration__Password: "${SMTP_PASSWORD}"
    ports:
      - "${PORT:-80}:80"
    depends_on:
      mssql:
        condition: service_healthy

volumes:
  mssql_data: