version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/API/Stocker.API/Dockerfile
    ports:
      - "5000:5000"
     
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - stocker-network

networks:
  stocker-network:
    driver: bridge
 