version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    volumes:
      - mssql_data:/var/opt/mssql
      - mssql_backup:/var/opt/mssql/backup
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrongPassword123!' -Q 'SELECT 1' -b -o /dev/null && echo 'healthy' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 60s
    networks:
      - stocker-network

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - stocker-network

  seq:
    image: datalust/seq:latest
    container_name: stocker-seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=StockerSeq2024!
    ports:
      - "5341:80"
      - "5342:5341"
    volumes:
      - seq_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - stocker-network

volumes:
  mssql_data:
    driver: local
  mssql_backup:
    driver: local
  redis_data:
    driver: local
  seq_data:
    driver: local

networks:
  stocker-network:
    driver: bridge