version: '3.8'

services:
  # API Service - Coolify optimized
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__MasterDb: ${DATABASE_URL}
      JwtSettings__SecretKey: ${JWT_SECRET_KEY}
      EmailSettings__SmtpHost: ${SMTP_HOST:-smtp.gmail.com}
      EmailSettings__SmtpPort: ${SMTP_PORT:-587}
      EmailSettings__SmtpUser: ${SMTP_USER}
      EmailSettings__SmtpPassword: ${SMTP_PASSWORD}
      EmailSettings__FromEmail: ${FROM_EMAIL:-noreply@stocker.com}
      EmailSettings__FromName: ${FROM_NAME:-Stocker}
    ports:
      - "${PORT:-80}:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Web Frontend - Coolify optimized
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      VITE_API_URL: ${FQDN}/api
      VITE_SIGNALR_URL: ${FQDN}/hubs
    depends_on:
      - api
    ports:
      - "${WEB_PORT:-3000}:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped