using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Stocker.Modules.Finance.Domain.Entities;

namespace Stocker.Modules.Finance.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity configuration for JournalEntry
/// </summary>
public class JournalEntryConfiguration : IEntityTypeConfiguration<JournalEntry>
{
    public void Configure(EntityTypeBuilder<JournalEntry> builder)
    {
        builder.ToTable("JournalEntries", "finance");

        builder.HasKey(je => je.Id);

        builder.Property(je => je.TenantId)
            .IsRequired();

        builder.Property(je => je.EntryNumber)
            .IsRequired()
            .HasMaxLength(50);

        builder.Property(je => je.Description)
            .IsRequired()
            .HasMaxLength(500);

        builder.Property(je => je.ReferenceType)
            .HasMaxLength(50);

        builder.Property(je => je.ReferenceNumber)
            .HasMaxLength(50);

        builder.Property(je => je.Currency)
            .IsRequired()
            .HasMaxLength(3)
            .HasDefaultValue("TRY");

        builder.Property(je => je.ApprovedBy)
            .HasMaxLength(200);

        // Money value objects - owned entities
        builder.OwnsOne(je => je.TotalDebit, money =>
        {
            money.Property(m => m.Amount).HasColumnName("TotalDebit").HasPrecision(18, 4);
            money.Property(m => m.Currency).HasColumnName("TotalDebitCurrency").HasMaxLength(3);
        });

        builder.OwnsOne(je => je.TotalCredit, money =>
        {
            money.Property(m => m.Amount).HasColumnName("TotalCredit").HasPrecision(18, 4);
            money.Property(m => m.Currency).HasColumnName("TotalCreditCurrency").HasMaxLength(3);
        });

        // Self-referencing relationship (Reversal)
        builder.HasOne(je => je.ReversedEntry)
            .WithMany()
            .HasForeignKey(je => je.ReversedEntryId)
            .OnDelete(DeleteBehavior.Restrict);

        // Relationships
        builder.HasOne(je => je.AccountingPeriod)
            .WithMany(ap => ap.JournalEntries)
            .HasForeignKey(je => je.AccountingPeriodId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasMany(je => je.Lines)
            .WithOne(l => l.JournalEntry)
            .HasForeignKey(l => l.JournalEntryId)
            .OnDelete(DeleteBehavior.Cascade);

        // Indexes
        builder.HasIndex(je => je.TenantId);
        builder.HasIndex(je => new { je.TenantId, je.EntryNumber }).IsUnique();
        builder.HasIndex(je => new { je.TenantId, je.EntryDate });
        builder.HasIndex(je => new { je.TenantId, je.EntryType });
        builder.HasIndex(je => new { je.TenantId, je.Status });
        builder.HasIndex(je => new { je.TenantId, je.IsAutoGenerated });
        builder.HasIndex(je => new { je.TenantId, je.IsReversal });
        builder.HasIndex(je => je.AccountingPeriodId);
        builder.HasIndex(je => je.ReferenceId);
    }
}

/// <summary>
/// Entity configuration for JournalEntryLine
/// </summary>
public class JournalEntryLineConfiguration : IEntityTypeConfiguration<JournalEntryLine>
{
    public void Configure(EntityTypeBuilder<JournalEntryLine> builder)
    {
        builder.ToTable("JournalEntryLines", "finance");

        builder.HasKey(l => l.Id);

        builder.Property(l => l.TenantId)
            .IsRequired();

        builder.Property(l => l.Description)
            .HasMaxLength(500);

        // Money value objects - owned entities (nullable)
        builder.OwnsOne(l => l.DebitAmount, money =>
        {
            money.Property(m => m.Amount).HasColumnName("DebitAmount").HasPrecision(18, 4);
            money.Property(m => m.Currency).HasColumnName("DebitAmountCurrency").HasMaxLength(3);
        });

        builder.OwnsOne(l => l.CreditAmount, money =>
        {
            money.Property(m => m.Amount).HasColumnName("CreditAmount").HasPrecision(18, 4);
            money.Property(m => m.Currency).HasColumnName("CreditAmountCurrency").HasMaxLength(3);
        });

        // Relationships
        builder.HasOne(l => l.JournalEntry)
            .WithMany(je => je.Lines)
            .HasForeignKey(l => l.JournalEntryId)
            .OnDelete(DeleteBehavior.Cascade);

        builder.HasOne(l => l.Account)
            .WithMany()
            .HasForeignKey(l => l.AccountId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne(l => l.CostCenter)
            .WithMany()
            .HasForeignKey(l => l.CostCenterId)
            .OnDelete(DeleteBehavior.SetNull);

        builder.HasOne(l => l.CurrentAccount)
            .WithMany()
            .HasForeignKey(l => l.CurrentAccountId)
            .OnDelete(DeleteBehavior.SetNull);

        // Indexes
        builder.HasIndex(l => l.TenantId);
        builder.HasIndex(l => l.JournalEntryId);
        builder.HasIndex(l => new { l.TenantId, l.JournalEntryId, l.LineNumber });
        builder.HasIndex(l => l.AccountId);
        builder.HasIndex(l => l.CostCenterId);
        builder.HasIndex(l => l.CurrentAccountId);
        builder.HasIndex(l => l.ProjectId);
    }
}
