version: '3.8'

# Prometheus Monitoring
# Metrics collection and alerting

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - coolify
    labels:
      - "com.stocker.service=monitoring"
      - "com.stocker.tier=infrastructure"
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`metrics.stoocker.app`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

volumes:
  prometheus_data:
    driver: local

networks:
  coolify:
    external: true