using Stocker.SharedKernel.Common;
using Stocker.Domain.Common.ValueObjects;

namespace Stocker.Modules.Finance.Domain.Entities;

/// <summary>
/// Yevmiye Kaydı (Journal Entry / Muhasebe Fişi)
/// Double-entry bookkeeping journal entry
/// </summary>
public class JournalEntry : BaseEntity
{
    /// <summary>
    /// Fiş Numarası (Entry Number) - Auto-generated
    /// </summary>
    public string EntryNumber { get; private set; } = string.Empty;

    /// <summary>
    /// Fiş Tarihi (Entry Date)
    /// </summary>
    public DateTime EntryDate { get; private set; }

    /// <summary>
    /// Fiş Türü (Entry Type)
    /// </summary>
    public JournalEntryType EntryType { get; private set; }

    /// <summary>
    /// Açıklama (Description)
    /// </summary>
    public string Description { get; private set; } = string.Empty;

    /// <summary>
    /// Referans Türü (Reference Type) - Invoice, Payment, etc.
    /// </summary>
    public string? ReferenceType { get; private set; }

    /// <summary>
    /// Referans Numarası (Reference Number)
    /// </summary>
    public string? ReferenceNumber { get; private set; }

    /// <summary>
    /// Referans ID
    /// </summary>
    public int? ReferenceId { get; private set; }

    /// <summary>
    /// Toplam Borç (Total Debit)
    /// </summary>
    public Money TotalDebit { get; private set; } = null!;

    /// <summary>
    /// Toplam Alacak (Total Credit)
    /// </summary>
    public Money TotalCredit { get; private set; } = null!;

    /// <summary>
    /// Para Birimi (Currency)
    /// </summary>
    public string Currency { get; private set; } = "TRY";

    /// <summary>
    /// Durum (Status)
    /// </summary>
    public JournalEntryStatus Status { get; private set; }

    /// <summary>
    /// Onaylayan (Approved By)
    /// </summary>
    public string? ApprovedBy { get; private set; }

    /// <summary>
    /// Onay Tarihi (Approval Date)
    /// </summary>
    public DateTime? ApprovalDate { get; private set; }

    /// <summary>
    /// Dönem ID (Accounting Period ID)
    /// </summary>
    public int AccountingPeriodId { get; private set; }

    /// <summary>
    /// Otomatik oluşturulmuş mu? (Is Auto-generated)
    /// </summary>
    public bool IsAutoGenerated { get; private set; }

    /// <summary>
    /// Ters kayıt mı? (Is Reversal Entry)
    /// </summary>
    public bool IsReversal { get; private set; }

    /// <summary>
    /// Tersine çevrilen kayıt ID (Reversed Entry ID)
    /// </summary>
    public int? ReversedEntryId { get; private set; }

    // Navigation Properties
    public virtual ICollection<JournalEntryLine> Lines { get; private set; } = new List<JournalEntryLine>();
    public virtual AccountingPeriod? AccountingPeriod { get; private set; }
    public virtual JournalEntry? ReversedEntry { get; private set; }

    protected JournalEntry() { }

    public JournalEntry(
        string entryNumber,
        DateTime entryDate,
        JournalEntryType entryType,
        string description,
        int accountingPeriodId,
        string currency = "TRY")
    {
        EntryNumber = entryNumber;
        EntryDate = entryDate;
        EntryType = entryType;
        Description = description;
        AccountingPeriodId = accountingPeriodId;
        Currency = currency;
        TotalDebit = Money.Zero(currency);
        TotalCredit = Money.Zero(currency);
        Status = JournalEntryStatus.Draft;
        IsAutoGenerated = false;
        IsReversal = false;
    }

    public void AddLine(JournalEntryLine line)
    {
        Lines.Add(line);
        RecalculateTotals();
    }

    public void RemoveLine(JournalEntryLine line)
    {
        Lines.Remove(line);
        RecalculateTotals();
    }

    public void SetReference(string referenceType, string referenceNumber, int? referenceId = null)
    {
        ReferenceType = referenceType;
        ReferenceNumber = referenceNumber;
        ReferenceId = referenceId;
    }

    public void MarkAsAutoGenerated()
    {
        IsAutoGenerated = true;
    }

    public void Submit()
    {
        if (Status != JournalEntryStatus.Draft)
            throw new InvalidOperationException("Only draft entries can be submitted");

        if (!IsBalanced())
            throw new InvalidOperationException("Journal entry is not balanced. Total debit must equal total credit.");

        Status = JournalEntryStatus.Pending;
    }

    public void Approve(string approvedBy)
    {
        if (Status != JournalEntryStatus.Pending)
            throw new InvalidOperationException("Only pending entries can be approved");

        Status = JournalEntryStatus.Approved;
        ApprovedBy = approvedBy;
        ApprovalDate = DateTime.UtcNow;
    }

    public void Post()
    {
        if (Status != JournalEntryStatus.Approved)
            throw new InvalidOperationException("Only approved entries can be posted");

        Status = JournalEntryStatus.Posted;
    }

    public void Reject(string reason)
    {
        if (Status != JournalEntryStatus.Pending)
            throw new InvalidOperationException("Only pending entries can be rejected");

        Status = JournalEntryStatus.Rejected;
        Description += $" [Rejected: {reason}]";
    }

    public void Void()
    {
        if (Status == JournalEntryStatus.Voided)
            throw new InvalidOperationException("Entry is already voided");

        Status = JournalEntryStatus.Voided;
    }

    public bool IsBalanced()
    {
        return TotalDebit.Amount == TotalCredit.Amount;
    }

    private void RecalculateTotals()
    {
        var totalDebit = Lines.Sum(l => l.DebitAmount?.Amount ?? 0);
        var totalCredit = Lines.Sum(l => l.CreditAmount?.Amount ?? 0);

        TotalDebit = Money.Create(totalDebit, Currency);
        TotalCredit = Money.Create(totalCredit, Currency);
    }

    /// <summary>
    /// Ters kayıt oluştur (Create reversal entry)
    /// </summary>
    public JournalEntry CreateReversal(string reversalNumber, DateTime reversalDate)
    {
        var reversal = new JournalEntry(
            reversalNumber,
            reversalDate,
            EntryType,
            $"Reversal of {EntryNumber}: {Description}",
            AccountingPeriodId,
            Currency)
        {
            IsReversal = true,
            ReversedEntryId = Id
        };

        // Swap debits and credits
        foreach (var line in Lines)
        {
            var reversalLine = new JournalEntryLine(
                reversal.Id,
                line.AccountId,
                line.CreditAmount, // Swap: credit becomes debit
                line.DebitAmount,  // Swap: debit becomes credit
                $"Reversal: {line.Description}");

            reversal.AddLine(reversalLine);
        }

        return reversal;
    }
}

/// <summary>
/// Yevmiye Kaydı Satırı (Journal Entry Line)
/// </summary>
public class JournalEntryLine : BaseEntity
{
    /// <summary>
    /// Yevmiye Kaydı ID (Journal Entry ID)
    /// </summary>
    public int JournalEntryId { get; private set; }

    /// <summary>
    /// Hesap ID (Account ID)
    /// </summary>
    public int AccountId { get; private set; }

    /// <summary>
    /// Borç Tutarı (Debit Amount)
    /// </summary>
    public Money? DebitAmount { get; private set; }

    /// <summary>
    /// Alacak Tutarı (Credit Amount)
    /// </summary>
    public Money? CreditAmount { get; private set; }

    /// <summary>
    /// Açıklama (Description)
    /// </summary>
    public string? Description { get; private set; }

    /// <summary>
    /// Masraf Merkezi ID (Cost Center ID)
    /// </summary>
    public int? CostCenterId { get; private set; }

    /// <summary>
    /// Proje ID (Project ID)
    /// </summary>
    public int? ProjectId { get; private set; }

    /// <summary>
    /// Cari Hesap ID (Current Account ID)
    /// </summary>
    public int? CurrentAccountId { get; private set; }

    /// <summary>
    /// Sıra No (Line Number)
    /// </summary>
    public int LineNumber { get; private set; }

    // Navigation Properties
    public virtual JournalEntry JournalEntry { get; private set; } = null!;
    public virtual Account Account { get; private set; } = null!;
    public virtual CostCenter? CostCenter { get; private set; }
    public virtual CurrentAccount? CurrentAccount { get; private set; }

    protected JournalEntryLine() { }

    public JournalEntryLine(
        int journalEntryId,
        int accountId,
        Money? debitAmount,
        Money? creditAmount,
        string? description = null)
    {
        if (debitAmount == null && creditAmount == null)
            throw new ArgumentException("Either debit or credit amount must be provided");

        if (debitAmount != null && creditAmount != null && debitAmount.Amount > 0 && creditAmount.Amount > 0)
            throw new ArgumentException("Cannot have both debit and credit on the same line");

        JournalEntryId = journalEntryId;
        AccountId = accountId;
        DebitAmount = debitAmount;
        CreditAmount = creditAmount;
        Description = description;
    }

    public void SetCostCenter(int costCenterId)
    {
        CostCenterId = costCenterId;
    }

    public void SetProject(int projectId)
    {
        ProjectId = projectId;
    }

    public void SetCurrentAccount(int currentAccountId)
    {
        CurrentAccountId = currentAccountId;
    }

    public void SetLineNumber(int lineNumber)
    {
        LineNumber = lineNumber;
    }
}

/// <summary>
/// Yevmiye Kaydı Türleri (Journal Entry Types)
/// </summary>
public enum JournalEntryType
{
    /// <summary>
    /// Açılış Fişi (Opening Entry)
    /// </summary>
    Opening = 1,

    /// <summary>
    /// Tahsilat Fişi (Collection Entry)
    /// </summary>
    Collection = 2,

    /// <summary>
    /// Tediye Fişi (Payment Entry)
    /// </summary>
    Payment = 3,

    /// <summary>
    /// Mahsup Fişi (Offset Entry)
    /// </summary>
    Offset = 4,

    /// <summary>
    /// Satış Faturası (Sales Invoice)
    /// </summary>
    SalesInvoice = 5,

    /// <summary>
    /// Alış Faturası (Purchase Invoice)
    /// </summary>
    PurchaseInvoice = 6,

    /// <summary>
    /// İade Faturası (Return Invoice)
    /// </summary>
    ReturnInvoice = 7,

    /// <summary>
    /// Genel Muhasebe (General Ledger)
    /// </summary>
    General = 8,

    /// <summary>
    /// Kapanış Fişi (Closing Entry)
    /// </summary>
    Closing = 9,

    /// <summary>
    /// Düzeltme Fişi (Adjustment Entry)
    /// </summary>
    Adjustment = 10,

    /// <summary>
    /// Transfer Fişi (Transfer Entry)
    /// </summary>
    Transfer = 11,

    /// <summary>
    /// Amortisman Fişi (Depreciation Entry)
    /// </summary>
    Depreciation = 12,

    /// <summary>
    /// Kur Farkı Fişi (Exchange Rate Difference Entry)
    /// </summary>
    ExchangeRateDifference = 13
}

/// <summary>
/// Yevmiye Kaydı Durumları (Journal Entry Statuses)
/// </summary>
public enum JournalEntryStatus
{
    /// <summary>
    /// Taslak (Draft)
    /// </summary>
    Draft = 1,

    /// <summary>
    /// Onay Bekliyor (Pending Approval)
    /// </summary>
    Pending = 2,

    /// <summary>
    /// Onaylandı (Approved)
    /// </summary>
    Approved = 3,

    /// <summary>
    /// Deftere İşlendi (Posted)
    /// </summary>
    Posted = 4,

    /// <summary>
    /// Reddedildi (Rejected)
    /// </summary>
    Rejected = 5,

    /// <summary>
    /// İptal Edildi (Voided)
    /// </summary>
    Voided = 6
}
