version: '3.8'

# SQL Server Database Service
# Deploy first as other services depend on it

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:-YourStrongPassword123!}
      - MSSQL_PID=${MSSQL_PID:-Express}
      - MSSQL_AGENT_ENABLED=true
      - MSSQL_ENABLE_HADR=0
      - MSSQL_TCP_PORT=1433
    volumes:
      - mssql_data:/var/opt/mssql
      - mssql_backup:/var/opt/mssql/backup
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '${SA_PASSWORD:-YourStrongPassword123!}' -Q 'SELECT 1' -b -o /dev/null"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 60s
    networks:
      - coolify
    labels:
      - "com.stocker.service=database"
      - "com.stocker.tier=infrastructure"

volumes:
  mssql_data:
    driver: local
  mssql_backup:
    driver: local

networks:
  coolify:
    external: true