version: '3.8'

# SQL Server Database Service
# Deploy first as other services depend on it

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: unless-stopped
    user: root  # Permission sorunlarını önlemek için
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID:-Developer}
      - MSSQL_AGENT_ENABLED=true
      - MSSQL_ENABLE_HADR=0
      - MSSQL_TCP_PORT=1433
      - MSSQL_COLLATION=Turkish_CI_AS
      - MSSQL_MEMORY_LIMIT_MB=2048
      - TZ=Europe/Istanbul
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_backup:/var/opt/mssql/backup
      - mssql_log:/var/opt/mssql/log
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '${SA_PASSWORD}' -Q 'SELECT 1' -b -o /dev/null"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 60s
    networks:
      - coolify
    labels:
      - "com.stocker.service=database"
      - "com.stocker.tier=infrastructure"
      - "coolify.managed=true"
    
    # Kaynak limitleri
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

volumes:
  mssql_data:
    driver: local
  mssql_backup:
    driver: local
  mssql_log:
    driver: local

networks:
  coolify:
    external: true