version: '3.8'

# Seq Logging - Public Access Version
# This configuration exposes Seq on seq.stoocker.app

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    ports:
      - "5341:80"  # Web UI and API
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_ADMIN_PASSWORD_HASH:-}
      - SEQ_CACHE_SYSTEMRAMTARGET=0.2
      - SEQ_STORAGE_SECRETKEY=${SEQ_SECRET_KEY:-}
    volumes:
      - seq_data:/data
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      
      # Seq Web UI
      - "traefik.http.routers.seq.rule=Host(`seq.stoocker.app`) || Host(`logs.stoocker.app`)"
      - "traefik.http.routers.seq.entrypoints=websecure"
      - "traefik.http.routers.seq.tls=true"
      - "traefik.http.routers.seq.tls.certresolver=letsencrypt"
      - "traefik.http.routers.seq.service=seq"
      - "traefik.http.services.seq.loadbalancer.server.port=80"
      
      # Basic auth middleware for security
      - "traefik.http.middlewares.seq-auth.basicauth.users=${SEQ_AUTH_USERS:-admin:$$2y$$10$$your-hashed-password}"
      - "traefik.http.routers.seq.middlewares=seq-auth"
      
      # Coolify labels
      - "coolify.managed=true"
      - "coolify.type=service"
      - "coolify.name=seq"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coolify

volumes:
  seq_data:
    external: true

networks:
  coolify:
    external: true