global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'stocker-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Stocker API metrics
  - job_name: 'stocker-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:5000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'stocker-api'

  # SQL Server metrics (if SQL Server exporter is added)
  - job_name: 'sqlserver'
    static_configs:
      - targets: ['sqlserver-exporter:4000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'stocker-mssql'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'stocker-redis'

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'stocker-rabbitmq'

  # ElasticSearch metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'stocker-elasticsearch'

  # MinIO metrics
  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['minio:9000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'stocker-minio'

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Alertmanager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']