version: '3.8'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_ADMIN_PASSWORD}
    volumes:
      - seq_data:/data
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      
      # HTTPS Router
      - "traefik.http.routers.seq-secure.rule=Host(`seq.stoocker.app`)"
      - "traefik.http.routers.seq-secure.entrypoints=https"
      - "traefik.http.routers.seq-secure.tls=true"
      - "traefik.http.routers.seq-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.seq-secure.tls.domains[0].main=stoocker.app"
      - "traefik.http.routers.seq-secure.tls.domains[0].sans=*.stoocker.app"
      - "traefik.http.routers.seq-secure.service=seq"
      - "traefik.http.services.seq.loadbalancer.server.port=80"
      
      # HTTP Router (redirect to HTTPS)
      - "traefik.http.routers.seq.rule=Host(`seq.stoocker.app`)"
      - "traefik.http.routers.seq.entrypoints=http"
      - "traefik.http.routers.seq.middlewares=seq-redirect"
      
      # Middleware definition
      - "traefik.http.middlewares.seq-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.seq-redirect.redirectscheme.permanent=true"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  seq_data:
    driver: local

networks:
  coolify:
    external: true