// Types
export * from './types/crm.types';
export * from './types/inventory.types';
export * from './types/hr.types';
export * from './types/sales.types';

// Services
export { crmService } from './services/crm.service';
export { inventoryService } from './services/inventory.service';
export { hrService } from './services/hr.service';
export { salesService } from './services/sales.service';

// Hooks - CRM
export {
    crmKeys,
    useCustomers,
    useCustomer,
    useCustomerActivities,
    useCreateCustomer,
    useUpdateCustomer,
    useDeleteCustomer,
    useDeals,
    useDeal,
    useUpdateDealStage,
    usePipelineStats,
    useSearchCustomers,
} from './hooks/useCRM';

// Hooks - Inventory
export {
    inventoryKeys,
    useProducts,
    useInfiniteProducts,
    useProduct,
    useProductStock,
    useProductByBarcode,
    useLowStockProducts,
    useTopSellingProducts,
    useSearchProducts,
    useCreateProduct,
    useUpdateProduct,
    useDeleteProduct,
    useStockMovements,
    useCreateStockMovement,
    useAdjustStock,
    useStockTransfers,
    useStockTransfer,
    useCreateStockTransfer,
    useApproveStockTransfer,
    useShipStockTransfer,
    useReceiveStockTransfer,
    useCancelStockTransfer,
    useStockCounts,
    useStockCount,
    useCreateStockCount,
    useUpdateStockCountItem,
    useCompleteStockCount,
    useCancelStockCount,
    useWarehouses,
    useWarehouse,
    useWarehouseStock,
    useCategories,
    useCategoryTree,
    useInventoryKPIs,
} from './hooks/useInventory';

// Hooks - HR
export {
    hrKeys,
    useEmployees,
    useEmployee,
    useCurrentEmployee,
    useSearchEmployees,
    useEmployeesByDepartment,
    useLeaveRequests,
    useLeaveRequest,
    useMyLeaveRequests,
    usePendingApprovals,
    useLeaveBalance,
    useLeaveCalendar,
    useCreateLeaveRequest,
    useUpdateLeaveRequest,
    useApproveLeaveRequest,
    useRejectLeaveRequest,
    useCancelLeaveRequest,
    useAttendance,
    useMyAttendance,
    useTodayAttendance,
    useMyTodayAttendance,
    useAttendanceSummary,
    useDailyAttendanceSummary,
    useCheckIn,
    useCheckOut,
    useDepartments,
    useDepartment,
    useDepartmentTree,
    usePositions,
    usePosition,
    useShifts,
    useShift,
    useHolidays,
    useUpcomingHolidays,
    useHRStats,
    useHRDashboard,
} from './hooks/useHR';

// Hooks - Sales
export {
    salesKeys,
    useOrders,
    useInfiniteOrders,
    useOrder,
    useRecentOrders,
    useSearchOrders,
    useCreateOrder,
    useUpdateOrder,
    useUpdateOrderStatus,
    useConfirmOrder,
    useCancelOrder,
    useDeleteOrder,
    useConvertOrderToInvoice,
    useInvoices,
    useInfiniteInvoices,
    useInvoice,
    useInvoicePayments,
    useOverdueInvoices,
    useSearchInvoices,
    useCreateInvoice,
    useUpdateInvoice,
    useSendInvoice,
    useMarkInvoiceAsPaid,
    useCancelInvoice,
    useDeleteInvoice,
    useQuotes,
    useInfiniteQuotes,
    useQuote,
    useExpiringQuotes,
    useCreateQuote,
    useUpdateQuote,
    useSendQuote,
    useAcceptQuote,
    useRejectQuote,
    useConvertQuoteToOrder,
    useDeleteQuote,
    useCreatePayment,
    usePayment,
    useRecentPayments,
    useDeletePayment,
    useSalesStats,
    useSalesSummary,
    useSalesDashboard,
    useSalesChart,
} from './hooks/useSales';

// Hooks - Global Search
export {
    useGlobalSearch,
    useRecentSearches,
    addRecentSearch,
    clearRecentSearches,
    SEARCH_CATEGORIES,
    type SearchResult,
    type GlobalSearchResults,
    type SearchCategory,
} from './hooks/useGlobalSearch';
