namespace Stocker.Modules.Manufacturing.Application.DTOs;

public record ProductionOrderDto(
    int Id,
    string OrderNumber,
    string Type,
    string Status,
    string Priority,
    int ProductId,
    string? ProductCode,
    string? ProductName,
    int? BomId,
    string? BomCode,
    int? RoutingId,
    string? RoutingCode,
    decimal PlannedQuantity,
    decimal CompletedQuantity,
    decimal ScrapQuantity,
    decimal ReworkQuantity,
    decimal CompletionPercent,
    string Unit,
    DateTime OrderDate,
    DateTime PlannedStartDate,
    DateTime PlannedEndDate,
    DateTime? ActualStartDate,
    DateTime? ActualEndDate,
    DateTime? DueDate,
    int? SourceWarehouseId,
    int? TargetWarehouseId,
    decimal? EstimatedMaterialCost,
    decimal? EstimatedLaborCost,
    decimal? EstimatedMachineCost,
    decimal? EstimatedOverheadCost,
    decimal? TotalEstimatedCost,
    decimal? ActualMaterialCost,
    decimal? ActualLaborCost,
    decimal? ActualMachineCost,
    decimal? ActualOverheadCost,
    decimal? TotalActualCost,
    int? SalesOrderId,
    int? SalesOrderLineId,
    int? ParentProductionOrderId,
    int? ProjectId,
    string? LotNumber,
    string? PlannedBy,
    string? ReleasedBy,
    DateTime? ReleasedDate,
    string? ClosedBy,
    DateTime? ClosedDate,
    string? Notes,
    DateTime CreatedDate,
    DateTime? UpdatedDate,
    IReadOnlyList<ProductionOrderLineDto> Lines,
    IReadOnlyList<ProductionOperationListDto> Operations);

public record ProductionOrderListDto(
    int Id,
    string OrderNumber,
    string Type,
    string Status,
    string Priority,
    int ProductId,
    string? ProductCode,
    string? ProductName,
    decimal PlannedQuantity,
    decimal CompletedQuantity,
    decimal CompletionPercent,
    DateTime PlannedStartDate,
    DateTime PlannedEndDate,
    DateTime? ActualStartDate,
    DateTime? DueDate);

public record ProductionOrderLineDto(
    int Id,
    int Sequence,
    int ProductId,
    string? ProductCode,
    string? ProductName,
    string LineType,
    decimal RequiredQuantity,
    decimal IssuedQuantity,
    decimal ScrapQuantity,
    string Unit,
    decimal UnitCost,
    decimal TotalCost,
    int? WarehouseId,
    string? WarehouseName,
    int? OperationId,
    bool IsBackflush,
    string? Notes);

public record CreateProductionOrderRequest(
    string Type,
    string Priority,
    int ProductId,
    int? BomId,
    int? RoutingId,
    decimal PlannedQuantity,
    string Unit,
    DateTime PlannedStartDate,
    DateTime PlannedEndDate,
    DateTime? DueDate,
    int? SourceWarehouseId,
    int? TargetWarehouseId,
    int? SalesOrderId,
    int? SalesOrderLineId,
    int? ParentProductionOrderId,
    int? ProjectId,
    string? LotNumber,
    string? Notes);

public record UpdateProductionOrderRequest(
    string Priority,
    decimal PlannedQuantity,
    string Unit,
    DateTime PlannedStartDate,
    DateTime PlannedEndDate,
    DateTime? DueDate,
    string? Notes);

public record StartProductionOrderRequest(
    DateTime? ActualStartDate);

public record CompleteProductionOrderRequest(
    decimal CompletedQuantity,
    decimal ScrapQuantity,
    string? Notes);

public record RecordProductionProgressRequest(
    decimal CompletedQuantity,
    decimal ScrapQuantity,
    string? Notes);
