namespace Stocker.Modules.Manufacturing.Application.DTOs;

public record RoutingDto(
    int Id,
    string Code,
    string Name,
    int ProductId,
    string? ProductCode,
    string? ProductName,
    string Version,
    int RevisionNumber,
    string Type,
    string Status,
    decimal BaseQuantity,
    string BaseUnit,
    DateTime? EffectiveStartDate,
    DateTime? EffectiveEndDate,
    decimal TotalSetupTime,
    decimal TotalRunTime,
    decimal TotalQueueTime,
    decimal TotalMoveTime,
    decimal TotalLeadTime,
    decimal? EstimatedLaborCost,
    decimal? EstimatedMachineCost,
    decimal? EstimatedOverheadCost,
    decimal? TotalEstimatedCost,
    bool IsDefault,
    bool IsActive,
    DateTime CreatedDate,
    string? ApprovedBy,
    DateTime? ApprovalDate,
    IReadOnlyList<OperationDto> Operations);

public record RoutingListDto(
    int Id,
    string Code,
    string Name,
    int ProductId,
    string? ProductCode,
    string? ProductName,
    string Version,
    string Type,
    string Status,
    int OperationCount,
    decimal TotalLeadTime,
    bool IsDefault,
    bool IsActive);

public record OperationDto(
    int Id,
    int Sequence,
    string Code,
    string Name,
    string Type,
    int WorkCenterId,
    string? WorkCenterCode,
    string? WorkCenterName,
    int? MachineId,
    string? MachineCode,
    decimal SetupTime,
    decimal RunTime,
    decimal QueueTime,
    decimal MoveTime,
    decimal TotalTime,
    decimal? SetupCost,
    decimal? RunCost,
    decimal? MachineCost,
    decimal? OverheadCost,
    decimal? TotalCost,
    int? MinimumWorkers,
    int? MaximumWorkers,
    bool IsSubcontracted,
    int? SubcontractorId,
    bool IsMilestone,
    bool RequiresQualityCheck,
    bool IsActive);

public record CreateRoutingRequest(
    string Code,
    string Name,
    int ProductId,
    string Type,
    string BaseUnit,
    decimal BaseQuantity = 1,
    DateTime? EffectiveStartDate = null,
    DateTime? EffectiveEndDate = null,
    string? Description = null,
    List<CreateOperationRequest>? Operations = null);

public record CreateOperationRequest(
    string Code,
    string Name,
    int WorkCenterId,
    int Sequence,
    string Type = "Üretim",
    int? MachineId = null,
    decimal SetupTime = 0,
    decimal RunTime = 0,
    decimal QueueTime = 0,
    decimal MoveTime = 0,
    int? MinimumWorkers = null,
    int? MaximumWorkers = null,
    bool IsSubcontracted = false,
    int? SubcontractorId = null,
    bool IsMilestone = false,
    bool RequiresQualityCheck = false,
    string? Notes = null);

public record UpdateRoutingRequest(
    string Name,
    string? Description,
    string Type,
    decimal BaseQuantity,
    string BaseUnit,
    DateTime? EffectiveStartDate,
    DateTime? EffectiveEndDate);

public record AddOperationRequest(
    string Code,
    string Name,
    int WorkCenterId,
    int Sequence,
    string Type = "Üretim",
    int? MachineId = null,
    decimal SetupTime = 0,
    decimal RunTime = 0,
    decimal QueueTime = 0,
    decimal MoveTime = 0,
    int? MinimumWorkers = null,
    int? MaximumWorkers = null,
    bool IsSubcontracted = false,
    int? SubcontractorId = null,
    bool IsMilestone = false,
    bool RequiresQualityCheck = false,
    string? Notes = null);
