using MediatR;
using Microsoft.EntityFrameworkCore;
using Stocker.Modules.Finance.Application.DTOs;
using Stocker.Modules.Finance.Application.Features.JournalEntries.Commands;
using Stocker.Modules.Finance.Domain.Entities;
using Stocker.Modules.Finance.Interfaces;
using Stocker.SharedKernel.MultiTenancy;
using Stocker.SharedKernel.Pagination;
using Stocker.SharedKernel.Results;

namespace Stocker.Modules.Finance.Application.Features.JournalEntries.Queries;

#region Get Journal Entries (Paginated with Filter)

/// <summary>
/// Query to get paginated journal entries with filtering
/// </summary>
public class GetJournalEntriesQuery : IRequest<Result<PagedResult<JournalEntrySummaryDto>>>, ITenantRequest
{
    public Guid TenantId { get; set; }
    public JournalEntryFilterDto? Filter { get; set; }
}

/// <summary>
/// Handler for GetJournalEntriesQuery
/// </summary>
public class GetJournalEntriesQueryHandler : IRequestHandler<GetJournalEntriesQuery, Result<PagedResult<JournalEntrySummaryDto>>>
{
    private readonly IFinanceUnitOfWork _unitOfWork;

    public GetJournalEntriesQueryHandler(IFinanceUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<Result<PagedResult<JournalEntrySummaryDto>>> Handle(GetJournalEntriesQuery request, CancellationToken cancellationToken)
    {
        IQueryable<JournalEntry> query = _unitOfWork.JournalEntries
            .AsQueryable()
            .Include(j => j.Lines);

        // Apply filters
        if (request.Filter != null)
        {
            // Search term filter
            if (!string.IsNullOrEmpty(request.Filter.SearchTerm))
            {
                var searchTerm = request.Filter.SearchTerm.ToLower();
                query = query.Where(j =>
                    j.EntryNumber.ToLower().Contains(searchTerm) ||
                    j.Description.ToLower().Contains(searchTerm) ||
                    (j.ReferenceNumber != null && j.ReferenceNumber.ToLower().Contains(searchTerm)));
            }

            // Entry type filter
            if (request.Filter.EntryType.HasValue)
            {
                query = query.Where(j => j.EntryType == request.Filter.EntryType.Value);
            }

            // Status filter
            if (request.Filter.Status.HasValue)
            {
                query = query.Where(j => j.Status == request.Filter.Status.Value);
            }

            // Date range filter
            if (request.Filter.StartDate.HasValue)
            {
                query = query.Where(j => j.EntryDate >= request.Filter.StartDate.Value);
            }

            if (request.Filter.EndDate.HasValue)
            {
                query = query.Where(j => j.EntryDate <= request.Filter.EndDate.Value);
            }

            // Accounting period filter
            if (request.Filter.AccountingPeriodId.HasValue)
            {
                query = query.Where(j => j.AccountingPeriodId == request.Filter.AccountingPeriodId.Value);
            }

            // Reference type filter
            if (!string.IsNullOrEmpty(request.Filter.ReferenceType))
            {
                query = query.Where(j => j.ReferenceType == request.Filter.ReferenceType);
            }

            // Reference ID filter
            if (request.Filter.ReferenceId.HasValue)
            {
                query = query.Where(j => j.ReferenceId == request.Filter.ReferenceId.Value);
            }

            // Account filter (entries containing lines with specific account)
            if (request.Filter.AccountId.HasValue)
            {
                query = query.Where(j => j.Lines.Any(l => l.AccountId == request.Filter.AccountId.Value));
            }

            // Flags filters
            if (request.Filter.IsAutoGenerated.HasValue)
            {
                query = query.Where(j => j.IsAutoGenerated == request.Filter.IsAutoGenerated.Value);
            }

            if (request.Filter.IsReversal.HasValue)
            {
                query = query.Where(j => j.IsReversal == request.Filter.IsReversal.Value);
            }

            if (request.Filter.IsBalanced.HasValue)
            {
                if (request.Filter.IsBalanced.Value)
                {
                    query = query.Where(j => j.TotalDebit.Amount == j.TotalCredit.Amount);
                }
                else
                {
                    query = query.Where(j => j.TotalDebit.Amount != j.TotalCredit.Amount);
                }
            }
        }

        // Get total count
        var totalCount = await query.CountAsync(cancellationToken);

        // Apply sorting
        var sortBy = request.Filter?.SortBy ?? "EntryDate";
        var sortDesc = request.Filter?.SortDescending ?? true;

        query = sortBy.ToLower() switch
        {
            "entrynumber" => sortDesc ? query.OrderByDescending(j => j.EntryNumber) : query.OrderBy(j => j.EntryNumber),
            "entrytype" => sortDesc ? query.OrderByDescending(j => j.EntryType) : query.OrderBy(j => j.EntryType),
            "status" => sortDesc ? query.OrderByDescending(j => j.Status) : query.OrderBy(j => j.Status),
            "totaldebit" => sortDesc ? query.OrderByDescending(j => j.TotalDebit.Amount) : query.OrderBy(j => j.TotalDebit.Amount),
            "totalcredit" => sortDesc ? query.OrderByDescending(j => j.TotalCredit.Amount) : query.OrderBy(j => j.TotalCredit.Amount),
            "description" => sortDesc ? query.OrderByDescending(j => j.Description) : query.OrderBy(j => j.Description),
            _ => sortDesc ? query.OrderByDescending(j => j.EntryDate) : query.OrderBy(j => j.EntryDate)
        };

        // Apply pagination
        var pageNumber = request.Filter?.PageNumber ?? 1;
        var pageSize = request.Filter?.PageSize ?? 20;

        var entries = await query
            .Skip((pageNumber - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync(cancellationToken);

        var dtos = entries.Select(MapToSummaryDto).ToList();

        return Result<PagedResult<JournalEntrySummaryDto>>.Success(
            new PagedResult<JournalEntrySummaryDto>(dtos, totalCount, pageNumber, pageSize));
    }

    private static JournalEntrySummaryDto MapToSummaryDto(JournalEntry entry)
    {
        return new JournalEntrySummaryDto
        {
            Id = entry.Id,
            EntryNumber = entry.EntryNumber,
            EntryDate = entry.EntryDate,
            EntryType = entry.EntryType,
            EntryTypeName = CreateJournalEntryCommandHandler.GetEntryTypeName(entry.EntryType),
            Description = entry.Description,
            TotalDebit = entry.TotalDebit.Amount,
            TotalCredit = entry.TotalCredit.Amount,
            Currency = entry.Currency,
            Status = entry.Status,
            StatusName = CreateJournalEntryCommandHandler.GetStatusName(entry.Status),
            IsBalanced = entry.IsBalanced(),
            IsAutoGenerated = entry.IsAutoGenerated,
            IsReversal = entry.IsReversal,
            LineCount = entry.Lines.Count
        };
    }
}

#endregion

#region Get Journal Entry By Id

/// <summary>
/// Query to get a journal entry by ID
/// </summary>
public class GetJournalEntryByIdQuery : IRequest<Result<JournalEntryDto>>, ITenantRequest
{
    public Guid TenantId { get; set; }
    public int Id { get; set; }
}

/// <summary>
/// Handler for GetJournalEntryByIdQuery
/// </summary>
public class GetJournalEntryByIdQueryHandler : IRequestHandler<GetJournalEntryByIdQuery, Result<JournalEntryDto>>
{
    private readonly IFinanceUnitOfWork _unitOfWork;

    public GetJournalEntryByIdQueryHandler(IFinanceUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<Result<JournalEntryDto>> Handle(GetJournalEntryByIdQuery request, CancellationToken cancellationToken)
    {
        var journalEntry = await _unitOfWork.JournalEntries
            .AsQueryable()
            .Include(j => j.Lines)
                .ThenInclude(l => l.Account)
            .Include(j => j.Lines)
                .ThenInclude(l => l.CostCenter)
            .Include(j => j.Lines)
                .ThenInclude(l => l.CurrentAccount)
            .Include(j => j.AccountingPeriod)
            .Include(j => j.ReversedEntry)
            .FirstOrDefaultAsync(j => j.Id == request.Id, cancellationToken);

        if (journalEntry == null)
        {
            return Result<JournalEntryDto>.Failure(
                Error.NotFound("JournalEntry", $"ID {request.Id} ile yevmiye kaydi bulunamadi"));
        }

        var dto = CreateJournalEntryCommandHandler.MapToDto(journalEntry);
        return Result<JournalEntryDto>.Success(dto);
    }
}

#endregion

#region Get Journal Entries By Type

/// <summary>
/// Query to get journal entries by type
/// </summary>
public class GetJournalEntriesByTypeQuery : IRequest<Result<PagedResult<JournalEntrySummaryDto>>>, ITenantRequest
{
    public Guid TenantId { get; set; }
    public JournalEntryType EntryType { get; set; }
    public int PageNumber { get; set; } = 1;
    public int PageSize { get; set; } = 20;
}

/// <summary>
/// Handler for GetJournalEntriesByTypeQuery
/// </summary>
public class GetJournalEntriesByTypeQueryHandler : IRequestHandler<GetJournalEntriesByTypeQuery, Result<PagedResult<JournalEntrySummaryDto>>>
{
    private readonly IFinanceUnitOfWork _unitOfWork;

    public GetJournalEntriesByTypeQueryHandler(IFinanceUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<Result<PagedResult<JournalEntrySummaryDto>>> Handle(GetJournalEntriesByTypeQuery request, CancellationToken cancellationToken)
    {
        var query = _unitOfWork.JournalEntries
            .AsQueryable()
            .Include(j => j.Lines)
            .Where(j => j.EntryType == request.EntryType);

        var totalCount = await query.CountAsync(cancellationToken);

        var entries = await query
            .OrderByDescending(j => j.EntryDate)
            .ThenByDescending(j => j.EntryNumber)
            .Skip((request.PageNumber - 1) * request.PageSize)
            .Take(request.PageSize)
            .ToListAsync(cancellationToken);

        var dtos = entries.Select(e => new JournalEntrySummaryDto
        {
            Id = e.Id,
            EntryNumber = e.EntryNumber,
            EntryDate = e.EntryDate,
            EntryType = e.EntryType,
            EntryTypeName = CreateJournalEntryCommandHandler.GetEntryTypeName(e.EntryType),
            Description = e.Description,
            TotalDebit = e.TotalDebit.Amount,
            TotalCredit = e.TotalCredit.Amount,
            Currency = e.Currency,
            Status = e.Status,
            StatusName = CreateJournalEntryCommandHandler.GetStatusName(e.Status),
            IsBalanced = e.IsBalanced(),
            IsAutoGenerated = e.IsAutoGenerated,
            IsReversal = e.IsReversal,
            LineCount = e.Lines.Count
        }).ToList();

        return Result<PagedResult<JournalEntrySummaryDto>>.Success(
            new PagedResult<JournalEntrySummaryDto>(dtos, totalCount, request.PageNumber, request.PageSize));
    }
}

#endregion

#region Get Journal Entries By Status

/// <summary>
/// Query to get journal entries by status
/// </summary>
public class GetJournalEntriesByStatusQuery : IRequest<Result<PagedResult<JournalEntrySummaryDto>>>, ITenantRequest
{
    public Guid TenantId { get; set; }
    public JournalEntryStatus Status { get; set; }
    public int PageNumber { get; set; } = 1;
    public int PageSize { get; set; } = 20;
}

/// <summary>
/// Handler for GetJournalEntriesByStatusQuery
/// </summary>
public class GetJournalEntriesByStatusQueryHandler : IRequestHandler<GetJournalEntriesByStatusQuery, Result<PagedResult<JournalEntrySummaryDto>>>
{
    private readonly IFinanceUnitOfWork _unitOfWork;

    public GetJournalEntriesByStatusQueryHandler(IFinanceUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<Result<PagedResult<JournalEntrySummaryDto>>> Handle(GetJournalEntriesByStatusQuery request, CancellationToken cancellationToken)
    {
        var query = _unitOfWork.JournalEntries
            .AsQueryable()
            .Include(j => j.Lines)
            .Where(j => j.Status == request.Status);

        var totalCount = await query.CountAsync(cancellationToken);

        var entries = await query
            .OrderByDescending(j => j.EntryDate)
            .ThenByDescending(j => j.EntryNumber)
            .Skip((request.PageNumber - 1) * request.PageSize)
            .Take(request.PageSize)
            .ToListAsync(cancellationToken);

        var dtos = entries.Select(e => new JournalEntrySummaryDto
        {
            Id = e.Id,
            EntryNumber = e.EntryNumber,
            EntryDate = e.EntryDate,
            EntryType = e.EntryType,
            EntryTypeName = CreateJournalEntryCommandHandler.GetEntryTypeName(e.EntryType),
            Description = e.Description,
            TotalDebit = e.TotalDebit.Amount,
            TotalCredit = e.TotalCredit.Amount,
            Currency = e.Currency,
            Status = e.Status,
            StatusName = CreateJournalEntryCommandHandler.GetStatusName(e.Status),
            IsBalanced = e.IsBalanced(),
            IsAutoGenerated = e.IsAutoGenerated,
            IsReversal = e.IsReversal,
            LineCount = e.Lines.Count
        }).ToList();

        return Result<PagedResult<JournalEntrySummaryDto>>.Success(
            new PagedResult<JournalEntrySummaryDto>(dtos, totalCount, request.PageNumber, request.PageSize));
    }
}

#endregion

#region Get Journal Entries By Period

/// <summary>
/// Query to get journal entries by accounting period
/// </summary>
public class GetJournalEntriesByPeriodQuery : IRequest<Result<PagedResult<JournalEntrySummaryDto>>>, ITenantRequest
{
    public Guid TenantId { get; set; }
    public int AccountingPeriodId { get; set; }
    public int PageNumber { get; set; } = 1;
    public int PageSize { get; set; } = 20;
}

/// <summary>
/// Handler for GetJournalEntriesByPeriodQuery
/// </summary>
public class GetJournalEntriesByPeriodQueryHandler : IRequestHandler<GetJournalEntriesByPeriodQuery, Result<PagedResult<JournalEntrySummaryDto>>>
{
    private readonly IFinanceUnitOfWork _unitOfWork;

    public GetJournalEntriesByPeriodQueryHandler(IFinanceUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<Result<PagedResult<JournalEntrySummaryDto>>> Handle(GetJournalEntriesByPeriodQuery request, CancellationToken cancellationToken)
    {
        var query = _unitOfWork.JournalEntries
            .AsQueryable()
            .Include(j => j.Lines)
            .Where(j => j.AccountingPeriodId == request.AccountingPeriodId);

        var totalCount = await query.CountAsync(cancellationToken);

        var entries = await query
            .OrderByDescending(j => j.EntryDate)
            .ThenByDescending(j => j.EntryNumber)
            .Skip((request.PageNumber - 1) * request.PageSize)
            .Take(request.PageSize)
            .ToListAsync(cancellationToken);

        var dtos = entries.Select(e => new JournalEntrySummaryDto
        {
            Id = e.Id,
            EntryNumber = e.EntryNumber,
            EntryDate = e.EntryDate,
            EntryType = e.EntryType,
            EntryTypeName = CreateJournalEntryCommandHandler.GetEntryTypeName(e.EntryType),
            Description = e.Description,
            TotalDebit = e.TotalDebit.Amount,
            TotalCredit = e.TotalCredit.Amount,
            Currency = e.Currency,
            Status = e.Status,
            StatusName = CreateJournalEntryCommandHandler.GetStatusName(e.Status),
            IsBalanced = e.IsBalanced(),
            IsAutoGenerated = e.IsAutoGenerated,
            IsReversal = e.IsReversal,
            LineCount = e.Lines.Count
        }).ToList();

        return Result<PagedResult<JournalEntrySummaryDto>>.Success(
            new PagedResult<JournalEntrySummaryDto>(dtos, totalCount, request.PageNumber, request.PageSize));
    }
}

#endregion

#region Get Journal Entry By Reference

/// <summary>
/// Query to get journal entries by reference
/// </summary>
public class GetJournalEntriesByReferenceQuery : IRequest<Result<List<JournalEntrySummaryDto>>>, ITenantRequest
{
    public Guid TenantId { get; set; }
    public string ReferenceType { get; set; } = string.Empty;
    public int ReferenceId { get; set; }
}

/// <summary>
/// Handler for GetJournalEntriesByReferenceQuery
/// </summary>
public class GetJournalEntriesByReferenceQueryHandler : IRequestHandler<GetJournalEntriesByReferenceQuery, Result<List<JournalEntrySummaryDto>>>
{
    private readonly IFinanceUnitOfWork _unitOfWork;

    public GetJournalEntriesByReferenceQueryHandler(IFinanceUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<Result<List<JournalEntrySummaryDto>>> Handle(GetJournalEntriesByReferenceQuery request, CancellationToken cancellationToken)
    {
        var entries = await _unitOfWork.JournalEntries
            .AsQueryable()
            .Include(j => j.Lines)
            .Where(j => j.ReferenceType == request.ReferenceType && j.ReferenceId == request.ReferenceId)
            .OrderByDescending(j => j.EntryDate)
            .ToListAsync(cancellationToken);

        var dtos = entries.Select(e => new JournalEntrySummaryDto
        {
            Id = e.Id,
            EntryNumber = e.EntryNumber,
            EntryDate = e.EntryDate,
            EntryType = e.EntryType,
            EntryTypeName = CreateJournalEntryCommandHandler.GetEntryTypeName(e.EntryType),
            Description = e.Description,
            TotalDebit = e.TotalDebit.Amount,
            TotalCredit = e.TotalCredit.Amount,
            Currency = e.Currency,
            Status = e.Status,
            StatusName = CreateJournalEntryCommandHandler.GetStatusName(e.Status),
            IsBalanced = e.IsBalanced(),
            IsAutoGenerated = e.IsAutoGenerated,
            IsReversal = e.IsReversal,
            LineCount = e.Lines.Count
        }).ToList();

        return Result<List<JournalEntrySummaryDto>>.Success(dtos);
    }
}

#endregion

#region Get Journal Entry Statistics

/// <summary>
/// Query to get journal entry statistics for a period
/// </summary>
public class GetJournalEntryStatisticsQuery : IRequest<Result<JournalEntryStatisticsDto>>, ITenantRequest
{
    public Guid TenantId { get; set; }
    public DateTime? StartDate { get; set; }
    public DateTime? EndDate { get; set; }
    public int? AccountingPeriodId { get; set; }
}

/// <summary>
/// Journal Entry Statistics DTO
/// </summary>
public class JournalEntryStatisticsDto
{
    public int TotalEntries { get; set; }
    public int DraftEntries { get; set; }
    public int PendingEntries { get; set; }
    public int ApprovedEntries { get; set; }
    public int PostedEntries { get; set; }
    public int RejectedEntries { get; set; }
    public int VoidedEntries { get; set; }
    public decimal TotalDebitAmount { get; set; }
    public decimal TotalCreditAmount { get; set; }
    public int UnbalancedEntries { get; set; }
    public int AutoGeneratedEntries { get; set; }
    public int ReversalEntries { get; set; }
    public Dictionary<string, int> EntriesByType { get; set; } = new();
}

/// <summary>
/// Handler for GetJournalEntryStatisticsQuery
/// </summary>
public class GetJournalEntryStatisticsQueryHandler : IRequestHandler<GetJournalEntryStatisticsQuery, Result<JournalEntryStatisticsDto>>
{
    private readonly IFinanceUnitOfWork _unitOfWork;

    public GetJournalEntryStatisticsQueryHandler(IFinanceUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<Result<JournalEntryStatisticsDto>> Handle(GetJournalEntryStatisticsQuery request, CancellationToken cancellationToken)
    {
        var query = _unitOfWork.JournalEntries.AsQueryable();

        // Apply date filters
        if (request.StartDate.HasValue)
        {
            query = query.Where(j => j.EntryDate >= request.StartDate.Value);
        }

        if (request.EndDate.HasValue)
        {
            query = query.Where(j => j.EntryDate <= request.EndDate.Value);
        }

        if (request.AccountingPeriodId.HasValue)
        {
            query = query.Where(j => j.AccountingPeriodId == request.AccountingPeriodId.Value);
        }

        var entries = await query.ToListAsync(cancellationToken);

        var statistics = new JournalEntryStatisticsDto
        {
            TotalEntries = entries.Count,
            DraftEntries = entries.Count(e => e.Status == JournalEntryStatus.Draft),
            PendingEntries = entries.Count(e => e.Status == JournalEntryStatus.Pending),
            ApprovedEntries = entries.Count(e => e.Status == JournalEntryStatus.Approved),
            PostedEntries = entries.Count(e => e.Status == JournalEntryStatus.Posted),
            RejectedEntries = entries.Count(e => e.Status == JournalEntryStatus.Rejected),
            VoidedEntries = entries.Count(e => e.Status == JournalEntryStatus.Voided),
            TotalDebitAmount = entries.Sum(e => e.TotalDebit.Amount),
            TotalCreditAmount = entries.Sum(e => e.TotalCredit.Amount),
            UnbalancedEntries = entries.Count(e => !e.IsBalanced()),
            AutoGeneratedEntries = entries.Count(e => e.IsAutoGenerated),
            ReversalEntries = entries.Count(e => e.IsReversal),
            EntriesByType = entries
                .GroupBy(e => e.EntryType)
                .ToDictionary(
                    g => CreateJournalEntryCommandHandler.GetEntryTypeName(g.Key),
                    g => g.Count())
        };

        return Result<JournalEntryStatisticsDto>.Success(statistics);
    }
}

#endregion
