version: '3.8'

# Stocker API Application
# Main backend service

services:
  api:
    image: ghcr.io/abrkgrbz/stocker-api:latest
    container_name: stocker-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # ASP.NET Core
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      
      # Database Connections
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=StockerTenantDb;User Id=sa;Password=${SA_PASSWORD:-YourStrongPassword123!};TrustServerCertificate=True;MultipleActiveResultSets=true
      - ConnectionStrings__MasterConnection=Server=mssql;Database=StockerMasterDb;User Id=sa;Password=${SA_PASSWORD:-YourStrongPassword123!};TrustServerCertificate=True;MultipleActiveResultSets=true
      - ConnectionStrings__TenantConnection=Server=mssql;Database=StockerTenantDb;User Id=sa;Password=${SA_PASSWORD:-YourStrongPassword123!};TrustServerCertificate=True;MultipleActiveResultSets=true
      
      # Redis
      - ConnectionStrings__Redis=redis:6379,password=${REDIS_PASSWORD:-RedisPassword123!}
      
      # Seq Logging
      - Logging__Seq__ServerUrl=http://seq:5341
      - Logging__Seq__ApiKey=${SEQ_API_KEY:-}
      
      # JWT
      - JwtSettings__Secret=${JWT_SECRET:-df7d992cdade60241c0c2443c421101028c4e2eeb5eb9e5f17da82fca026c73a}
      - JwtSettings__Issuer=https://api.stoocker.app
      - JwtSettings__Audience=https://stoocker.app
      
      # Email (Namecheap Private Email)
      - EmailSettings__SmtpHost=mail.privateemail.com
      - EmailSettings__SmtpPort=465
      - EmailSettings__SmtpUsername=info@stoocker.app
      - EmailSettings__SmtpPassword=${SMTP_PASSWORD:-A.bg010203}
      - EmailSettings__FromEmail=info@stoocker.app
      - EmailSettings__FromName=Stoocker
      - EmailSettings__EnableSsl=true
      - EmailSettings__UseStartTls=false
      
      # MinIO
      - Storage__Provider=MinIO
      - Storage__MinIO__Endpoint=minio:9000
      - Storage__MinIO__AccessKey=${MINIO_ROOT_USER:-admin}
      - Storage__MinIO__SecretKey=${MINIO_ROOT_PASSWORD:-MinioPassword123!}
      - Storage__MinIO__BucketName=stocker-files
      - Storage__MinIO__UseSSL=false
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coolify
    labels:
      - "com.stocker.service=api"
      - "com.stocker.tier=application"
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.stoocker.app`)"
      - "traefik.http.services.api.loadbalancer.server.port=5000"
      # WebSocket support for SignalR
      - "traefik.http.middlewares.api-websocket.headers.customrequestheaders.Connection=keep-alive"
      - "traefik.http.middlewares.api-websocket.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.routers.api.middlewares=api-websocket"

networks:
  coolify:
    external: true