version: '3.8'

# Stocker Web - Wildcard subdomain support
# This configuration handles all tenant subdomains automatically

services:
  web:
    build:
      context: ../../../stocker-web
      dockerfile: Dockerfile
    container_name: stocker-web
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.stoocker.app
      - VITE_APP_URL=https://stoocker.app
      - VITE_MASTER_URL=https://master.stoocker.app
    labels:
      # Coolify labels for automatic SSL
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=stocker-web"
      
      # Main domain
      - "coolify.domain=stoocker.app"
      
      # WWW redirect
      - "coolify.www.domain=www.stoocker.app"
      - "coolify.www.redirect=stoocker.app"
      
      # Wildcard for all subdomains (Coolify will generate SSL for each)
      # Each subdomain will get its own Let's Encrypt certificate automatically
      - "coolify.wildcard=true"
      - "coolify.wildcard.domain=*.stoocker.app"
      
      # Exclude specific subdomains that have their own services
      - "coolify.wildcard.exclude=api,master,admin,www"
      
      # Auto-generate SSL for new subdomains
      - "coolify.ssl.auto=true"
      - "coolify.ssl.email=info@stoocker.app"
      
      # Health check
      - "coolify.healthcheck.enabled=true"
      - "coolify.healthcheck.path=/"
      - "coolify.healthcheck.interval=30"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coolify

networks:
  coolify:
    external: true