version: '3.8'

# Stocker Web Application - Coolify Optimized Version
# This version is specifically for Coolify deployment

services:
  web:
    # Option 1: Build from GitHub (Recommended for Coolify)
    build:
      context: https://github.com/yourusername/stocker.git#main
      dockerfile: stocker-web/Dockerfile
    
    # Option 2: Build from local path (if Coolify has access to repo)
    # build:
    #   context: .
    #   dockerfile: stocker-web/Dockerfile
    
    # Option 3: Use pre-built image (fastest)
    # image: ghcr.io/yourusername/stocker-web:latest
    
    container_name: stocker-web
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.stoocker.app
      - VITE_APP_URL=https://stoocker.app
      - VITE_MOCK_ENABLED=false
      - VITE_SEQ_URL=http://95.217.219.4:5341
      - VITE_MASTER_URL=https://master.stoocker.app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coolify
    labels:
      # Coolify specific labels
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=stocker-web"
      
      # Domain configuration for Coolify
      # Add all your domains here separated by comma
      - "coolify.domains=stoocker.app,www.stoocker.app,demo.stoocker.app,techstart.stoocker.app,master.stoocker.app"
      
      # SSL configuration
      - "coolify.ssl.auto=true"
      - "coolify.ssl.email=info@stoocker.app"
      
      # Standard labels
      - "com.stocker.service=web"
      - "com.stocker.tier=application"

networks:
  coolify:
    external: true