version: '3.8'

# Stocker Web Application
# Frontend React application - Built from source by Coolify

services:
  web:
    build:
      context: .
      dockerfile: ./stocker-web/Dockerfile
    container_name: stocker-web
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=https://api.stoocker.app
      - VITE_APP_URL=https://stoocker.app
      - VITE_MOCK_ENABLED=false
      - VITE_SEQ_URL=https://seq.stoocker.app
      - VITE_MINIO_URL=https://s3.stoocker.app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coolify
    labels:
      - "com.stocker.service=web"
      - "com.stocker.tier=application"
      - "traefik.enable=true"
      # Main domain
      - "traefik.http.routers.web.rule=Host(`stoocker.app`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      # WWW redirect
      - "traefik.http.routers.web-www.rule=Host(`www.stoocker.app`)"
      - "traefik.http.routers.web-www.middlewares=www-redirect"
      - "traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www.(.*)"
      - "traefik.http.middlewares.www-redirect.redirectregex.replacement=https://$$1"
      # Master subdomain
      - "traefik.http.routers.web-master.rule=Host(`master.stoocker.app`)"
      - "traefik.http.routers.web-master.service=web"

networks:
  coolify:
    external: true