version: '3.8'

# Stocker Auth Application (Next.js)
# Handles authentication and registration on auth subdomain

services:
  auth:
    build:
      context: .
      dockerfile: ./stocker-nextjs/Dockerfile
    container_name: stocker-auth
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.stoocker.app
      - NEXT_PUBLIC_APP_URL=https://auth.stoocker.app
      - NEXT_PUBLIC_MAIN_APP_URL=https://stoocker.app
      - NEXT_TELEMETRY_DISABLED=1

    networks:
      - coolify

    labels:
      # COOLIFY CONFIGURATION FOR AUTH SUBDOMAIN
      # IMPORTANT: Leave FQDN empty in Coolify UI for this to work

      - "traefik.enable=true"
      - "traefik.docker.network=coolify"

      # Auth subdomain router (auth.stoocker.app)
      - "traefik.http.routers.stocker-auth.rule=Host(`auth.stoocker.app`)"
      - "traefik.http.routers.stocker-auth.entrypoints=https"
      - "traefik.http.routers.stocker-auth.tls=true"
      - "traefik.http.routers.stocker-auth.tls.certresolver=cloudflare"
      - "traefik.http.routers.stocker-auth.service=stocker-auth-service"
      - "traefik.http.routers.stocker-auth.priority=15"

      # HTTP -> HTTPS redirect
      - "traefik.http.routers.stocker-auth-http.rule=Host(`auth.stoocker.app`)"
      - "traefik.http.routers.stocker-auth-http.entrypoints=http"
      - "traefik.http.routers.stocker-auth-http.middlewares=redirect-https"

      # Service definition - Next.js runs on port 3000
      - "traefik.http.services.stocker-auth-service.loadbalancer.server.port=3000"

      # Middleware for HTTPS redirect
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  coolify:
    external: true
