version: '3.8'

# Stocker Admin Panel
# Admin dashboard for system management - Built from source by Coolify

services:
  admin:
    build:
      context: .
      dockerfile: ./stocker-admin/Dockerfile
    container_name: stocker-admin
    restart: unless-stopped
    ports:
      - "3010:80"
    environment:
      - VITE_API_URL=https://api.stoocker.app
      - VITE_APP_URL=https://admin.stoocker.app
      - VITE_MOCK_ENABLED=false
      - VITE_SEQ_URL=https://seq.stoocker.app
      - VITE_MINIO_URL=https://s3.stoocker.app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coolify
    labels:
      - "com.stocker.service=admin"
      - "com.stocker.tier=application"
      - "traefik.enable=true"
      # Admin subdomain
      - "traefik.http.routers.admin.rule=Host(`admin.stoocker.app`)"
      - "traefik.http.services.admin.loadbalancer.server.port=80"
      # SSL/TLS
      - "traefik.http.routers.admin.tls=true"
      - "traefik.http.routers.admin.tls.certresolver=letsencrypt"
      # Security headers
      - "traefik.http.middlewares.admin-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.admin-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.admin-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.admin-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.admin-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.admin-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.admin-headers.headers.stsSeconds=31536000"
      - "traefik.http.routers.admin.middlewares=admin-headers"

networks:
  coolify:
    external: true