// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stocker.Modules.CMS.Infrastructure.Persistence;

#nullable disable

namespace Stocker.Modules.CMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CMSDbContext))]
    [Migration("20260127120000_AddDeletedByColumn")]
    partial class AddDeletedByColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cms")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is a partial migration - inherits from previous snapshot
            // Only adding DeletedBy column to all CMS tables
            // CMS already has IsDeleted and DeletedAt columns
#pragma warning restore 612, 618
        }
    }
}
