using Stocker.Modules.Finance.Domain.Entities;

namespace Stocker.Modules.Finance.Application.DTOs;

/// <summary>
/// Yevmiye Kaydı DTO (Journal Entry DTO)
/// Full details including lines
/// </summary>
public class JournalEntryDto
{
    public int Id { get; set; }
    public string EntryNumber { get; set; } = string.Empty;
    public DateTime EntryDate { get; set; }
    public JournalEntryType EntryType { get; set; }
    public string EntryTypeName { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;

    // Reference
    public string? ReferenceType { get; set; }
    public string? ReferenceNumber { get; set; }
    public int? ReferenceId { get; set; }

    // Amounts
    public decimal TotalDebit { get; set; }
    public decimal TotalCredit { get; set; }
    public string Currency { get; set; } = "TRY";
    public bool IsBalanced { get; set; }

    // Status
    public JournalEntryStatus Status { get; set; }
    public string StatusName { get; set; } = string.Empty;

    // Approval
    public string? ApprovedBy { get; set; }
    public DateTime? ApprovalDate { get; set; }

    // Period
    public int AccountingPeriodId { get; set; }
    public string? AccountingPeriodName { get; set; }

    // Flags
    public bool IsAutoGenerated { get; set; }
    public bool IsReversal { get; set; }
    public int? ReversedEntryId { get; set; }
    public string? ReversedEntryNumber { get; set; }

    // Lines
    public List<JournalEntryLineDto> Lines { get; set; } = new();

    // Audit
    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
}

/// <summary>
/// Yevmiye Kaydı Özet DTO (Journal Entry Summary DTO)
/// For list views
/// </summary>
public class JournalEntrySummaryDto
{
    public int Id { get; set; }
    public string EntryNumber { get; set; } = string.Empty;
    public DateTime EntryDate { get; set; }
    public JournalEntryType EntryType { get; set; }
    public string EntryTypeName { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public decimal TotalDebit { get; set; }
    public decimal TotalCredit { get; set; }
    public string Currency { get; set; } = "TRY";
    public JournalEntryStatus Status { get; set; }
    public string StatusName { get; set; } = string.Empty;
    public bool IsBalanced { get; set; }
    public bool IsAutoGenerated { get; set; }
    public bool IsReversal { get; set; }
    public int LineCount { get; set; }
}

/// <summary>
/// Yevmiye Kaydı Satır DTO (Journal Entry Line DTO)
/// </summary>
public class JournalEntryLineDto
{
    public int Id { get; set; }
    public int JournalEntryId { get; set; }
    public int LineNumber { get; set; }

    // Account
    public int AccountId { get; set; }
    public string? AccountCode { get; set; }
    public string? AccountName { get; set; }

    // Amounts
    public decimal? DebitAmount { get; set; }
    public decimal? CreditAmount { get; set; }
    public string? Currency { get; set; }

    // Details
    public string? Description { get; set; }

    // Optional references
    public int? CostCenterId { get; set; }
    public string? CostCenterName { get; set; }
    public int? ProjectId { get; set; }
    public string? ProjectName { get; set; }
    public int? CurrentAccountId { get; set; }
    public string? CurrentAccountName { get; set; }
}

/// <summary>
/// Yevmiye Kaydı Oluşturma DTO (Create Journal Entry DTO)
/// </summary>
public class CreateJournalEntryDto
{
    public DateTime EntryDate { get; set; }
    public JournalEntryType EntryType { get; set; }
    public string Description { get; set; } = string.Empty;
    public int AccountingPeriodId { get; set; }
    public string Currency { get; set; } = "TRY";

    // Optional reference
    public string? ReferenceType { get; set; }
    public string? ReferenceNumber { get; set; }
    public int? ReferenceId { get; set; }

    // Lines
    public List<CreateJournalEntryLineDto> Lines { get; set; } = new();
}

/// <summary>
/// Yevmiye Kaydı Satır Oluşturma DTO (Create Journal Entry Line DTO)
/// </summary>
public class CreateJournalEntryLineDto
{
    public int AccountId { get; set; }
    public decimal? DebitAmount { get; set; }
    public decimal? CreditAmount { get; set; }
    public string? Description { get; set; }

    // Optional references
    public int? CostCenterId { get; set; }
    public int? ProjectId { get; set; }
    public int? CurrentAccountId { get; set; }
}

/// <summary>
/// Yevmiye Kaydı Güncelleme DTO (Update Journal Entry DTO)
/// </summary>
public class UpdateJournalEntryDto
{
    public DateTime? EntryDate { get; set; }
    public string? Description { get; set; }
    public string? ReferenceType { get; set; }
    public string? ReferenceNumber { get; set; }
    public int? ReferenceId { get; set; }

    // Lines to update
    public List<UpdateJournalEntryLineDto>? Lines { get; set; }
}

/// <summary>
/// Yevmiye Kaydı Satır Güncelleme DTO (Update Journal Entry Line DTO)
/// </summary>
public class UpdateJournalEntryLineDto
{
    public int? Id { get; set; } // Null for new lines
    public int AccountId { get; set; }
    public decimal? DebitAmount { get; set; }
    public decimal? CreditAmount { get; set; }
    public string? Description { get; set; }
    public int? CostCenterId { get; set; }
    public int? ProjectId { get; set; }
    public int? CurrentAccountId { get; set; }
}

/// <summary>
/// Yevmiye Kaydı Filtre DTO (Journal Entry Filter DTO)
/// </summary>
public class JournalEntryFilterDto
{
    public int PageNumber { get; set; } = 1;
    public int PageSize { get; set; } = 20;
    public string? SearchTerm { get; set; }

    // Type and Status filters
    public JournalEntryType? EntryType { get; set; }
    public JournalEntryStatus? Status { get; set; }

    // Date filters
    public DateTime? StartDate { get; set; }
    public DateTime? EndDate { get; set; }

    // Period filter
    public int? AccountingPeriodId { get; set; }

    // Reference filters
    public string? ReferenceType { get; set; }
    public int? ReferenceId { get; set; }

    // Account filter
    public int? AccountId { get; set; }

    // Flags
    public bool? IsAutoGenerated { get; set; }
    public bool? IsReversal { get; set; }
    public bool? IsBalanced { get; set; }

    // Sorting
    public string? SortBy { get; set; }
    public bool SortDescending { get; set; } = true;
}

/// <summary>
/// Yevmiye Kaydı Onay DTO (Approve Journal Entry DTO)
/// </summary>
public class ApproveJournalEntryDto
{
    public string ApprovedBy { get; set; } = string.Empty;
}

/// <summary>
/// Yevmiye Kaydı Reddetme DTO (Reject Journal Entry DTO)
/// </summary>
public class RejectJournalEntryDto
{
    public string Reason { get; set; } = string.Empty;
}

/// <summary>
/// Ters Kayıt Oluşturma DTO (Create Reversal Entry DTO)
/// </summary>
public class CreateReversalEntryDto
{
    public DateTime ReversalDate { get; set; }
    public string? Description { get; set; }
}
