// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stocker.Persistence.Contexts;

#nullable disable

namespace Stocker.Persistence.Migrations.TenantDb
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260127100000_AddDeletedByToChatMessages")]
    partial class AddDeletedByToChatMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenant")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is a partial migration - inherits from previous snapshot
            // Only adding DeletedBy column to ChatMessages table
#pragma warning restore 612, 618
        }
    }
}
