version: '3.8'

services:
  stocker-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stocker-web:latest
    container_name: stocker-web
    environment:
      # API URL - Runtime değişken olarak nginx'e geçirilecek
      VITE_API_URL: ${VITE_API_URL:-http://localhost:5000}
    ports:
      - "${WEB_PORT:-3000}:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - stocker-network

networks:
  stocker-network:
    driver: bridge